name: flutter_aula_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - images/bitcoin.png
    - images/cardano.png
    - images/litecoin.png
    - images/usdcoin.png
    - images/ethereum.png
    - images/xrp.png


  uses-material-design: true
  